"""Split the legacy monolithic trade log (``logs/trades/trades.jsonl``) into
date-partitioned archives under ``logs/trades/archive/YYYY/MM/YYYY-MM-DD.jsonl``.

Writes a migration manifest and a holding file for undated or malformed
records. The source log is treated as read-only until the finalize step;
see :func:`parse_args` for the full option set.

Usage::

    python scripts/migrate_trade_logs.py --src PATH --dest-root PATH
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import uuid
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SRC = REPO_ROOT / "logs" / "trades" / "trades.jsonl"
DEFAULT_DEST_ROOT = REPO_ROOT / "logs" / "trades"
LEGACY_DIR_NAME = "legacy"
MANIFEST_NAME = "migration-manifest.json"
HOLDING_FILE_NAME = "trades-undated-or-malformed.jsonl"


class MigrationError(RuntimeError):
    """Raised when migration inputs or output state are unsafe."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Split the legacy monolithic trade log into archive/YYYY/MM/YYYY-MM-DD.jsonl partitions"
    )
    parser.add_argument(
        "--src",
        default=str(DEFAULT_SRC),
        help="Path to the legacy monolithic trade log (default: logs/trades/trades.jsonl)",
    )
    parser.add_argument(
        "--dest-root",
        default=str(DEFAULT_DEST_ROOT),
        help="Destination trade root (default/preferred: logs/trades/)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Scan and report without writing any output files",
    )
    parser.add_argument(
        "--overwrite-generated",
        action="store_true",
        help="Replace only files previously generated by this migration tool",
    )
    return parser.parse_args()


def parse_iso_ts(value: Any) -> datetime | None:
    if not isinstance(value, str) or not value.strip():
        return None
    try:
        dt = datetime.fromisoformat(value)
    except ValueError:
        return None
    if dt.tzinfo is None:
        return dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc)


def _manifest_path(dest_root: Path) -> Path:
    return dest_root / LEGACY_DIR_NAME / MANIFEST_NAME


def _holding_path(dest_root: Path) -> Path:
    return dest_root / LEGACY_DIR_NAME / HOLDING_FILE_NAME


def _archive_relpath(day_key: str) -> str:
    year, month, _ = day_key.split("-")
    return f"archive/{year}/{month}/{day_key}.jsonl"


def _load_manifest(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise MigrationError(f"Could not read manifest at {path}: {exc}") from exc


def _finalize_output(source_path: Path, target_path: Path) -> None:
    target_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        os.replace(source_path, target_path)
    except PermissionError:
        shutil.copy2(source_path, target_path)


def _remove_generated_outputs(
    dest_root: Path,
    manifest: dict[str, Any],
    src: Path,
    current_generated_files: list[str],
) -> None:
    manifest_src = str(manifest.get("src") or "")
    # Normalize paths as strings to avoid pathlib property access issues on Windows/Python 3.14
    manifest_src_normalized = os.path.normcase(os.path.normpath(os.fspath(Path(manifest_src).resolve())))
    src_normalized = os.path.normcase(os.path.normpath(os.fspath(src.resolve())))
    if manifest_src_normalized != src_normalized:
        raise MigrationError(
            "--overwrite-generated refused: manifest source does not match requested --src"
        )
    for relpath in manifest.get("generated_files", []):
        if relpath in current_generated_files:
            continue
        target = dest_root / relpath
        if target.exists():
            target.unlink()


def _assert_safe_outputs(
    *,
    dest_root: Path,
    generated_files: list[str],
    src: Path,
    overwrite_generated: bool,
) -> None:
    manifest_path = _manifest_path(dest_root)
    manifest = _load_manifest(manifest_path)
    if overwrite_generated:
        if manifest is None:
            raise MigrationError(
                "--overwrite-generated requires an existing migration manifest"
            )
        _remove_generated_outputs(dest_root, manifest, src, generated_files)
        return

    existing = [str(dest_root / relpath) for relpath in generated_files if (dest_root / relpath).exists()]
    if manifest is not None:
        raise MigrationError(
            f"Migration manifest already exists at {manifest_path}; rerun with --overwrite-generated"
        )
    if existing:
        raise MigrationError(
            "Migration would overwrite existing files:\n" + "\n".join(existing[:10])
        )


def _new_summary(src: Path, dest_root: Path, dry_run: bool, overwrite_generated: bool) -> dict[str, Any]:
    return {
        "src": str(src.resolve()),
        "dest_root": str(dest_root.resolve()),
        "dry_run": dry_run,
        "overwrite_generated": overwrite_generated,
        "input_lines_read": 0,
        "migrated_records_written": 0,
        "undated_or_malformed_count": 0,
        "per_day_counts": {},
        "event_type_counts": {},
        "generated_files": [],
        "reconciled": False,
    }


def migrate_legacy_trade_log(
    src: Path,
    dest_root: Path,
    *,
    dry_run: bool = False,
    overwrite_generated: bool = False,
) -> dict[str, Any]:
    if not src.exists():
        raise MigrationError(f"Source file not found: {src}")
    if src.is_dir():
        raise MigrationError(f"Source must be a file, not a directory: {src}")

    summary = _new_summary(src, dest_root, dry_run, overwrite_generated)
    day_counts: Counter[str] = Counter()
    event_counts: Counter[str] = Counter()
    temp_root: Path | None = None
    partition_handles: dict[str, Any] = {}
    holding_handle = None

    try:
        if not dry_run:
            temp_root = dest_root / LEGACY_DIR_NAME / f".migration-{uuid.uuid4().hex}"
            temp_root.mkdir(parents=True, exist_ok=False)

        with src.open("r", encoding="utf-8") as handle:
            for raw_line in handle:
                summary["input_lines_read"] += 1
                line = raw_line.rstrip("\n")
                if not line.strip():
                    continue

                try:
                    record = json.loads(line)
                except json.JSONDecodeError:
                    summary["undated_or_malformed_count"] += 1
                    if not dry_run:
                        if holding_handle is None:
                            holding_path = temp_root / LEGACY_DIR_NAME / HOLDING_FILE_NAME
                            holding_path.parent.mkdir(parents=True, exist_ok=True)
                            holding_handle = holding_path.open("a", encoding="utf-8", newline="\n")
                        holding_handle.write(line + "\n")
                    continue

                if not isinstance(record, dict):
                    summary["undated_or_malformed_count"] += 1
                    if not dry_run:
                        if holding_handle is None:
                            holding_path = temp_root / LEGACY_DIR_NAME / HOLDING_FILE_NAME
                            holding_path.parent.mkdir(parents=True, exist_ok=True)
                            holding_handle = holding_path.open("a", encoding="utf-8", newline="\n")
                        holding_handle.write(line + "\n")
                    continue

                ts = parse_iso_ts(record.get("ts"))
                if ts is None:
                    summary["undated_or_malformed_count"] += 1
                    if not dry_run:
                        if holding_handle is None:
                            holding_path = temp_root / LEGACY_DIR_NAME / HOLDING_FILE_NAME
                            holding_path.parent.mkdir(parents=True, exist_ok=True)
                            holding_handle = holding_path.open("a", encoding="utf-8", newline="\n")
                        holding_handle.write(line + "\n")
                    continue

                day_key = ts.date().isoformat()
                day_counts[day_key] += 1
                event_type = str(record.get("type") or record.get("event") or "UNKNOWN").strip() or "UNKNOWN"
                event_counts[event_type] += 1
                summary["migrated_records_written"] += 1

                if dry_run:
                    continue

                if day_key not in partition_handles:
                    relpath = Path(_archive_relpath(day_key))
                    partition_path = temp_root / relpath
                    partition_path.parent.mkdir(parents=True, exist_ok=True)
                    partition_handles[day_key] = partition_path.open("a", encoding="utf-8", newline="\n")
                partition_handles[day_key].write(line + "\n")

        for file_handle in partition_handles.values():
            file_handle.close()
        if holding_handle is not None:
            holding_handle.close()

        summary["per_day_counts"] = dict(sorted(day_counts.items()))
        summary["event_type_counts"] = dict(sorted(event_counts.items()))

        generated_files = [_archive_relpath(day_key) for day_key in sorted(day_counts)]
        if summary["undated_or_malformed_count"] > 0:
            generated_files.append(f"{LEGACY_DIR_NAME}/{HOLDING_FILE_NAME}")
        generated_files.append(f"{LEGACY_DIR_NAME}/{MANIFEST_NAME}")
        summary["generated_files"] = generated_files
        summary["reconciled"] = (
            summary["input_lines_read"]
            == summary["migrated_records_written"] + summary["undated_or_malformed_count"]
        )

        if dry_run:
            return summary

        _assert_safe_outputs(
            dest_root=dest_root,
            generated_files=generated_files,
            src=src,
            overwrite_generated=overwrite_generated,
        )

        manifest = dict(summary)
        manifest_path = temp_root / LEGACY_DIR_NAME / MANIFEST_NAME
        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")

        for relpath in generated_files:
            source_path = temp_root / relpath
            if not source_path.exists():
                continue
            target_path = dest_root / relpath
            _finalize_output(source_path, target_path)

        return summary
    finally:
        for file_handle in partition_handles.values():
            try:
                file_handle.close()
            except Exception:
                pass
        if holding_handle is not None:
            try:
                holding_handle.close()
            except Exception:
                pass
        if temp_root is not None and temp_root.exists():
            shutil.rmtree(temp_root, ignore_errors=True)


def print_summary(summary: dict[str, Any]) -> None:
    print("TRADE LOG MIGRATION")
    print(f"Source                : {summary['src']}")
    print(f"Destination root      : {summary['dest_root']}")
    print(f"Dry run               : {'yes' if summary['dry_run'] else 'no'}")
    print(f"Overwrite generated   : {'yes' if summary['overwrite_generated'] else 'no'}")
    print(f"Input lines read      : {summary['input_lines_read']}")
    print(f"Migrated records      : {summary['migrated_records_written']}")
    print(f"Undated / malformed   : {summary['undated_or_malformed_count']}")
    print(f"Reconciled            : {'yes' if summary['reconciled'] else 'no'}")
    print()
    print("Per-Day Counts")
    if summary["per_day_counts"]:
        for day, count in summary["per_day_counts"].items():
            print(f"  {day}: {count}")
    else:
        print("  (none)")
    print()
    print("Event Type Counts")
    if summary["event_type_counts"]:
        for event_type, count in summary["event_type_counts"].items():
            print(f"  {event_type}: {count}")
    else:
        print("  (none)")


def main() -> int:
    args = parse_args()
    summary = migrate_legacy_trade_log(
        Path(args.src),
        Path(args.dest_root),
        dry_run=args.dry_run,
        overwrite_generated=args.overwrite_generated,
    )
    print_summary(summary)
    if not summary["reconciled"]:
        raise SystemExit("Input totals did not reconcile")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
